name: Blameless SLO Deploy

on:
    push:
        branches: [main]

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/blameless-cli
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
                  scope: '@blamelesshq'
                  always-auth: true
            - run: npm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
