name: Blameless SLO Deploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/blameless-cli
        steps:
            - name: 'Setup actions'
              uses: actions/checkout@v2
            - name: 'NPM/Registry Setup'
              uses: actions/setup-node@v1
              with:
                  node-version: 14
                  registry-url: https://npm.pkg.github.com/
                  scope: '@blamelesshq'
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: "Publish Package"
              uses: actions/bin/debug@master
              run: |
                echo registry=https://npm.pkg.github.com/blamelesshq >> .npmrc
                npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
