name: Blameless SLO Validator

on:
    push:
        branches:
            - main

jobs:
    publish-gpr:
        runs-on: ubuntu-latest
        env:
          working-directory: ./packages/blameless-slo-validator
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.gitub.com/
                  scope: '@blamelesshq'
            working-directory: ${{env.working-directory}}
            - run: npm install
            working-directory: ${{env.working-directory}}
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
